version: "3.9"
services:
  test:
    build:
      context: ./test
      args:
        BASE_IMAGE: "${DOCKER_IMAGE}"
    env_file:
      - .env.backend
      - .env.db
    environment:
      PYTHONPATH: /
    networks:
      - recipe-backend
    depends_on:
      - webserver

networks:
  recipe-backend:
