version: "3.9"
services:
  webserver:
    image: "${DOCKER_IMAGE}"
    ports:
      - "80:80"
    volumes:
      - "${PWD}/src:/src"
    env_file:
      - .env.backend
      - .env.db
    networks:
      - recipe-backend

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    networks:
      - recipe-backend

networks:
  recipe-backend: